### PR TITLE
Implemented aborting sources in abortAll

### PR DESCRIPTION
**Pull request by clehner**

### CODE REVIEW

**Comment by mixmix** [comment]
The tests look legit.
I don't follow the abortAll logic completely but I can confirm that this PR is the difference between a highly performant private thread mod in Ticktack and one that doesn't work at all (well, I have to revert to scanning all private messages).

I'd recommend this is merged and published.
@dominictarr I'm happy to merge this, but you've got npm publish permissions

**Comment by dominictarr** [comment]
this is perfect, thanks! sorry I missed this!

**Comment by dominictarr** [comment]
merged into 1.0.4

**Comment by mixmix** [comment]
this is great. It's going to make finding private threads with a particular friend super fast!

**Pull request merged**
